### ISSUE TITLE
Add metadata for GATE and LDC data types

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/Galaxy#2]

**Comment by ksuderman** [comment]
Refresh my memory.  What do you mean by "metadata for GATE and LDC data types"?

**Comment by marcverhagen** [comment]
Good question. Could someone remind me of what I meant back in December?

I guess we keep this for a few days to give me a chance to remember, and otherwise close it.

**Comment by keighrim** [comment]
Was it for adding @type for LDC data and gate format? I don't remember neither. Should we close this now?

**Comment by marcverhagen** [comment]
Mayhap. I will close this.
