### ISSUE TITLE
Uploading data is not working 

### ISSUE THREAD

**Issue by keighrim** [lappsgrid-incubator/Galaxy#6]
Uploading local files or pasting text to start a workflow is not working, maybe after merging with the new galaxy.  I'll look into it. 
``` 
Traceback (most recent call last):
  File "/home/galaxy/mods/tools/data_source/upload.py", line 434, in <module>
    __main__()
  File "/home/galaxy/mods/tools/data_source/upload.py", line 413, in __main__
    dataset = util.bunch.Bunch( **safe_dict( dataset ) )
TypeError: type object argument after ** must be a mapping, not list
```

**Comment by ksuderman** [comment]
The Galaxy project rewrote the upload tool, but it was not copied over to our GalaxyMods tools directory.  Testing now.

**Comment by ksuderman** [comment]
When this happens in the future copy `./galaxy/tools/data_source/upload.*` to `./mods/tools/data_source`
